name: docker-hello-world

on: push

jobs:
  vm:
    runs-on: self-hosted
    steps:
      - name: Run on the VM directly
        run: |
          echo "hello world from the VM"

  container:
    runs-on: self-hosted
    container: alpine
    steps:
      - name: Run in container
        run: |
          echo "hello world from Docker"
